### ISSUE TITLE
Trailer menu not working

### ISSUE THREAD

**Issue by huettern** [saidolsol/mensabot_js#4]
Receiving
```
/trailer
Diese Mensa hat kein Menu zur Verfügung gestellt, vermutlich ist sie heute geschlossen. :cry:
```

**Comment by saidolsol** [comment]
Auf https://ethz.ch/de/campus/erleben/gastronomie-und-einkaufen/gastronomie.html wurde kein Menü hochgeladen :(

**Comment by huettern** [comment]
unter https://ethz.ch/en/campus/getting-to-know/cafes-restaurants-shops/gastronomy/menueplaene/offerDay.html?language=en&id=9&date=2019-12-13 kann ich es finden

**Comment by gingeneer** [comment]
ist gefixed, mit neuer version der API
